baseURL = "https://lhao03.github.io/"
languageCode = "en-us"
title = "Lucy Hao | Computer Science Student at UBC"

[permalinks]
    blog = "blog/:filename/"

[menu]
  [[menu.main]]
    name = "home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "blog"
    pre = "blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "courses"
    pre = "courses"
    url = "/classes/"
    weight = 3
  [[menu.main]]
    name = "projects"
    pre = "projects"
    url = "/projects/"
    weight = 4
  [[menu.main]]
    name = "failures"
    pre = "failures"
    url = "/failures/"
    weight = 5

  [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"